### ISSUE TITLE
ERROR Short name 'PhpIncludeInspection' is not unique

### ISSUE THREAD

**Issue by vokamut** [vizh/bxfs#2]
```
2017-11-30 09:45:50,608 [  10930]  ERROR - ion.ex.InspectionToolRegistrar - Short name 'PhpIncludeInspection' is not unique
class 'pro.opcode.bitrix.inspections.PhpIncludeInspection' in PluginDescriptor[name='Bitrix Framework Support', classpath='C:\Users\Tumakov\.PhpStorm2017.3\config\plugins\bitrix.jar']
and
class'com.jetbrains.php.lang.inspections.PhpIncludeInspection' in PluginDescriptor[name='PHP', classpath='C:\Program Files\JetBrains\PhpStorm 2017.2.4\plugins\php']
conflict [Plugin: pro.opcode.bitrix] 
com.intellij.diagnostic.PluginException: Short name 'PhpIncludeInspection' is not unique
class 'pro.opcode.bitrix.inspections.PhpIncludeInspection' in PluginDescriptor[name='Bitrix Framework Support', classpath='C:\Users\Tumakov\.PhpStorm2017.3\config\plugins\bitrix.jar']
and
class'com.jetbrains.php.lang.inspections.PhpIncludeInspection' in PluginDescriptor[name='PHP', classpath='C:\Program Files\JetBrains\PhpStorm 2017.2.4\plugins\php']
conflict [Plugin: pro.opcode.bitrix]
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.a(InspectionToolRegistrar.java:86)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.a(InspectionToolRegistrar.java:60)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.createTools(InspectionToolRegistrar.java:127)
	at com.intellij.codeInspection.ex.InspectionSearchableOptionContributor.processOptions(InspectionSearchableOptionContributor.java:34)
	at com.intellij.ide.ui.search.SearchableOptionPreloader.preload(SearchableOptionPreloader.java:49)
	at com.intellij.openapi.application.Preloader.a(Preloader.java:74)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:534)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:479)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.application.Preloader.a(Preloader.java:72)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
2017-11-30 09:45:50,611 [  10933]  ERROR - ion.ex.InspectionToolRegistrar - PhpStorm 2017.3  Build #PS-173.3727.138 
2017-11-30 09:45:50,611 [  10933]  ERROR - ion.ex.InspectionToolRegistrar - JDK: 9.0.1 
2017-11-30 09:45:50,611 [  10933]  ERROR - ion.ex.InspectionToolRegistrar - VM: Java HotSpot(TM) 64-Bit Server VM 
2017-11-30 09:45:50,611 [  10933]  ERROR - ion.ex.InspectionToolRegistrar - Vendor: Oracle Corporation 
2017-11-30 09:45:50,611 [  10933]  ERROR - ion.ex.InspectionToolRegistrar - OS: Windows 10 
2017-11-30 09:45:50,611 [  10933]  ERROR - ion.ex.InspectionToolRegistrar - Last Action:  
```

**Comment by ReWiG** [comment]
Действительно вываливается такая ошибка после последнего обновления PHPSTORM

**Comment by toFlash** [comment]
присоединяюсь к просьбе об исправлении ошибки )

**Comment by AndyOrbis** [comment]
Исправил в форке: https://github.com/AndyOrbis/bxfs. Ошибка, как я понял, ни на что по сути не влияла для пользователя расширения.
Ошибка вылетала из-за того, что для Code Inspections в новой библиотеке php.jar уже зарезервировано Short name 'PhpIncludeInspection'. Заменил в плагине имя на уникальное.
Вроде, автор уже не занимается этим плагином, поэтому без Pull Request`а.

**Comment by vizh** [comment]
Да, увы я уже очень давно не с Битрикс и под конец года работы навалило так, что всё откладывал разобраться. Получилось слишком долго откладывать. Если организуешь pull request, то смерджу и организую обновление.

Спасибо! Я всё ждал, что разработку подхватит комьюнити.

**Comment by AndyOrbis** [comment]
@vizh, хорошо, завтра сделаю. И спасибо за полезный плагин! :-)

**Comment by toFlash** [comment]
@AndyOrbis спасибо! теперь дело за автором @vizh !

**Comment by ReWiG** [comment]
Обновления стоит ждать в ближайшее время?

**Comment by vokamut** [comment]
Я у себя вручную исправил(согласно пул реквесту), не стал ждать обновления.
А конкретнее внутри файла ~/.PhpStorm2017.3/config/plugins/bitrix.jar
В файле META-INF/plugin.xml
Заменил PhpIncludeInspection на BxPhpIncludeInspection
