### ISSUE TITLE
com.jetbrains.php.lang.psi.elements.impl.ConcatenationExpressionImpl cannot be cast to com.jetbrains.php.lang.psi.elements.StringLiteralExpression

### ISSUE THREAD

**Issue by vokamut** [vizh/bxfs#4]
com.jetbrains.php.lang.psi.elements.impl.ConcatenationExpressionImpl cannot be cast to com.jetbrains.php.lang.psi.elements.StringLiteralExpression
    java.lang.ClassCastException: com.jetbrains.php.lang.psi.elements.impl.ConcatenationExpressionImpl cannot be cast to com.jetbrains.php.lang.psi.elements.StringLiteralExpression
        at pro.opcode.bitrix.api.BxComponent.<init>(BxComponent.java:27)
        at pro.opcode.bitrix.api.BxCore.getComponent(BxCore.java:30)
        at pro.opcode.bitrix.references.BxComponentTemplateReference.resolve(BxComponentTemplateReference.java:18)
        at pro.opcode.bitrix.BxReference.getReference(BxReference.java:67)
        at pro.opcode.bitrix.BxReferenceContributors$2.getReferencesByElement(BxReferenceContributors.java:22)
        at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.getReferences(ReferenceProvidersRegistryImpl.java:135)
        at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.mapNotEmptyReferencesFromProviders(ReferenceProvidersRegistryImpl.java:123)
        at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:102)
        at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:59)
        at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:53)
        at com.jetbrains.php.lang.psi.elements.impl.StringLiteralExpressionImpl.getReferences(StringLiteralExpressionImpl.java:294)
        at org.intellij.plugins.intelliLang.references.InjectedReferencesContributor.getInjectedReferences(InjectedReferencesContributor.java:56)
        at org.intellij.plugins.intelliLang.references.InjectedReferencesInspection$1.visitElement(InjectedReferencesInspection.java:40)
        at com.jetbrains.php.lang.psi.elements.impl.StringLiteralExpressionImpl.accept(StringLiteralExpressionImpl.java:29)
        at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:82)
        at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:309)
        at com.intellij.concurrency.ApplierCompleter.d(ApplierCompleter.java:133)
        at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:223)
        at com.intellij.concurrency.ApplierCompleter.d(ApplierCompleter.java:151)
        at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:223)
        at com.intellij.concurrency.ApplierCompleter.d(ApplierCompleter.java:151)
        at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1127)
        at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:105)
        at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
        at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:116)
        at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:96)
        at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
        at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:229)
        at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

    com.jetbrains.php.lang.psi.elements.impl.ConcatenationExpressionImpl cannot be cast to com.jetbrains.php.lang.psi.elements.StringLiteralExpression
    java.lang.ClassCastException: com.jetbrains.php.lang.psi.elements.impl.ConcatenationExpressionImpl cannot be cast to com.jetbrains.php.lang.psi.elements.StringLiteralExpression
        at pro.opcode.bitrix.api.BxComponent.<init>(BxComponent.java:27)
        at pro.opcode.bitrix.api.BxCore.getComponent(BxCore.java:30)
        at pro.opcode.bitrix.references.BxComponentTemplateReference.resolve(BxComponentTemplateReference.java:18)
        at pro.opcode.bitrix.BxReference.getReference(BxReference.java:67)
        at pro.opcode.bitrix.BxReferenceContributors$2.getReferencesByElement(BxReferenceContributors.java:22)
        at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.getReferences(ReferenceProvidersRegistryImpl.java:135)
        at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.mapNotEmptyReferencesFromProviders(ReferenceProvidersRegistryImpl.java:123)
        at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:102)
        at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:59)
        at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:53)
        at com.jetbrains.php.lang.psi.elements.impl.StringLiteralExpressionImpl.getReferences(StringLiteralExpressionImpl.java:294)
        at org.intellij.plugins.intelliLang.references.InjectedReferencesContributor.getInjectedReferences(InjectedReferencesContributor.java:56)
        at org.intellij.plugins.intelliLang.references.InjectedReferencesInspection$1.visitElement(InjectedReferencesInspection.java:40)
        at com.jetbrains.php.lang.psi.elements.impl.StringLiteralExpressionImpl.accept(StringLiteralExpressionImpl.java:29)
        at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:82)
        at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:309)
        at com.intellij.concurrency.ApplierCompleter.d(ApplierCompleter.java:133)
        at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:223)
        at com.intellij.concurrency.ApplierCompleter.d(ApplierCompleter.java:151)
        at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1127)
        at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:105)
        at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
        at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:116)
        at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:96)
        at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
        at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:229)
        at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

    java.lang.ClassCastException: com.jetbrains.php.lang.psi.elements.impl.ConcatenationExpressionImpl cannot be cast to com.jetbrains.php.lang.psi.elements.StringLiteralExpression
        at pro.opcode.bitrix.api.BxComponent.<init>(BxComponent.java:27)
        at pro.opcode.bitrix.api.BxCore.getComponent(BxCore.java:30)
        at pro.opcode.bitrix.references.BxComponentTemplateReference.resolve(BxComponentTemplateReference.java:18)
        at pro.opcode.bitrix.BxReference.getReference(BxReference.java:67)
        at pro.opcode.bitrix.BxReferenceContributors$2.getReferencesByElement(BxReferenceContributors.java:22)
        at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.getReferences(ReferenceProvidersRegistryImpl.java:135)
        at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.mapNotEmptyReferencesFromProviders(ReferenceProvidersRegistryImpl.java:123)
        at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:102)
        at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:59)
        at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:53)
        at com.jetbrains.php.lang.psi.elements.impl.StringLiteralExpressionImpl.getReferences(StringLiteralExpressionImpl.java:294)
        at org.intellij.plugins.intelliLang.references.InjectedReferencesContributor.getInjectedReferences(InjectedReferencesContributor.java:56)
        at org.intellij.plugins.intelliLang.references.InjectedReferencesInspection$1.visitElement(InjectedReferencesInspection.java:40)
        at com.jetbrains.php.lang.psi.elements.impl.StringLiteralExpressionImpl.accept(StringLiteralExpressionImpl.java:29)
        at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:82)
        at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:309)
        at com.intellij.concurrency.ApplierCompleter.d(ApplierCompleter.java:133)
        at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:223)
        at com.intellij.concurrency.ApplierCompleter.d(ApplierCompleter.java:151)
        at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1127)
        at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:105)
        at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
        at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:116)
        at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:96)
        at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
        at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:229)
        at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by vizh** [comment]
Проблема возникает при открытии какого-то конкретного файла или перманентно?

**Comment by vokamut** [comment]
Я не нашел способ воспроизвести ошибку, появилось впервые и после перезапуска IDE больше не возникает

**Comment by vizh** [comment]
Эта и подобные ей проблемы должны кануть в лету с выходом 0.1.9 версии, которую загрузил сейчас в JetBrains Plugins Repository. Должна стать доступной для скачивания в начале следующего года после ревью со стороны Jetbrains.
